// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;
using SilentOrbit.ProtocolBuffers;
using OxidePack;

namespace OxidePack.Data
{
    public partial class UserInformation : IDisposable, Pool.IPooled, IProto
    {
        public string key;

        public string username;

    }

    public partial class GeneratedFileRequest : IDisposable, Pool.IPooled, IProto
    {
        public string pluginname;

        public List<string> modules;

    }

    public partial class GeneratedFileResponse : IDisposable, Pool.IPooled, IProto
    {
        public string pluginname;

        public string content;

    }

    public partial class BuildRequest : IDisposable, Pool.IPooled, IProto
    {
        public OxidePack.Data.BuildOptions options;

        public List<OxidePack.Data.SourceFile> sources;

    }

    public partial class BuildOptions : IDisposable, Pool.IPooled, IProto
    {
        public string name;

    }

    public partial class SourceFile : IDisposable, Pool.IPooled, IProto
    {
        public string filename;

        public string content;

        public string sha256;

    }

}
